### ISSUE TITLE
Which Programming Language

### ISSUE THREAD

**Issue by mwhittaker** [mwhittaker/raft#1]
Hey @ambarsoni, @yuxiaotan, @alugupta,

What programming language would you guys like to use for this project? I know I was pretty set on rust, but I thought about it more and now am unsure. Particularly, rust won't be stable for quite some time, most likely not until after summer ends. Having to update the code base would be unfun; having to use an outdated compiler would be unfun. Perhaps something more mature like go would be more appropriate. What are your thoughts?

Best,
Michael

**Comment by ambarsoni** [comment]
I'd go for Go

**Comment by mwhittaker** [comment]
Good one Ambar! I was leaning towards go as well.

**Comment by yuxiaotan** [comment]
I would be down for Go as well

Yuxiao Tan
Cornell Engineering 2016

**Comment by mwhittaker** [comment]
Awesome! Unless there's a resounding nay from @alugupta, I'd say we're going go.

**Comment by mwhittaker** [comment]
Hey Guys,

So with the recent release of [cargo](http://crates.io/), with some nice [makefiles](https://github.com/bvssvni/rust-empty) to help development, and after reading [this question](http://www.reddit.com/r/rust/comments/23538h/is_rust_worth_starting_projects_in_now_or_is_it/), I think that Rust would actually be more instructive and more fun than Go. I think that our code base will be small enough that we could keep up with the nightly builds. What do you guys think?

Best,
Michael

**Comment by yuxiaotan** [comment]
If you insist ;)

On Fri, Jun 27, 2014 at 8:20 AM, Michael Whittaker <notifications@github.com

> wrote:
> 
> Hey Guys,
> 
> So with the recent release of cargo http://crates.io/, with some nice
> makefiles https://github.com/bvssvni/rust-empty to help development,
> and after reading this question
> http://www.reddit.com/r/rust/comments/23538h/is_rust_worth_starting_projects_in_now_or_is_it/,
> I think that Rust would actually be more instructive and more fun than Go.
> I think that our code base will be small enough that we could keep up with
> the nightly builds. What do you guys think?
> 
> Best,
> Michael
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mwhittaker/raft/issues/1#issuecomment-47359564.

## 

Yuxiao Tan
Cornell Electrical and Computer Engineering '16
Baja Electronics Team
yt358@cornell.edu
(c)240-205-3023

**Comment by mwhittaker** [comment]
Ya'll are too nice :smile:

**Comment by mwhittaker** [comment]
@ambarsoni, @alugupta, thoughts?

**Comment by ambarsoni** [comment]
Im pretty ambivalent on the language, sorry I've had a tight schedule with
my office here so ill contribute as much as I can. Im confused as to what
the days allocated for rust/raft are.

Just to clarify, raft is the algorithm and rust is the language right?

-milz <3

**Comment by mwhittaker** [comment]
Hey Ambar,

> Im pretty ambivalent on the language

I think you'll like rust!

> sorry I've had a tight schedule with my office here so ill contribute as much as I can

No worries dude! Contribute as much as you can as leisurely as you want. 

> Im confused as to what the days allocated for rust/raft are

If you go the [milestones page](https://github.com/mwhittaker/raft/issues/milestones), the due dates are listed under the titles of each milestone. [Learn Rust](https://github.com/mwhittaker/raft/issues?milestone=1&state=open), for example, is due July 7.

> Just to clarify, raft is the algorithm and rust is the language right?

Yes sir! The links in the milestones have a wealth of information on both.

:heart: Michael

**Comment by mwhittaker** [comment]
I'm also going to take @alugupta's silence as an overwhelmingly positive support for rust, and I'll go ahead and close this issue.
