### ISSUE TITLE
Small comments made

### ISSUE THREAD

**Issue by yuxiaotan** [mwhittaker/raft#5]
Will close when resolved. Why does Github not have an automatic thing to do this.

**Comment by mwhittaker** [comment]
I think it makes more sense not to open an issue for every round of comments on a pull request. Resolving the pull request will resolve the comments.

**Comment by yuxiaotan** [comment]
I agree with first sentence. I don't fully understand the second, could you elaborate?

**Comment by mwhittaker** [comment]
> Will close when resolved.

You said you'd close this issue when the comments on the pull request were resolved. When we resolve and close the pull request, it implies we've resolved the comment, so we don't need an extra issue to close.

**Comment by mwhittaker** [comment]
But yeah, it would be cool to have comments in rounds where you could explicitly signal you've responded to someone's round of comments. That would be neat.

**Comment by yuxiaotan** [comment]
Yeah that's exactly what I mean. I'm guessing mongo does it?

**Comment by mwhittaker** [comment]
Some teams use Github for code review; other teams use other code review tools, so it depends on the team.

**Comment by yuxiaotan** [comment]
TBH I don't like Github code review. There seems to be very little accountability

**Comment by mwhittaker** [comment]
I agree. If Github integrated a super good code review tool, that would be so nice.
